name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Set up ENV vars
      run: touch app.properties && echo "DEV_API_BASE_URL=\"${{ secrets.API_DEBUG }}\"" > app.properties && cat app.properties && echo "PROD_API_BASE_URL=\"${{ secrets.API_DEBUG }}\"" >> app.properties && cat app.properties  && echo "API_KEY=\"${{ secrets.API_KEY }}\"" >> app.properties && cat app.properties
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run JVM unit tests
      run: ./gradlew test
    - name: Build debug app
      run: ./gradlew assembleDebug
    - name: Upload debug build
      uses: actions/upload-artifact@v3.0.0
      with:
        name: debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
